# Fine-tuning with Unsloth

based on the tutorial:
https://docs.unsloth.ai/basics/tutorial-how-to-finetune-llama-3-and-use-in-ollama

##### In this notebook, we fine-tune models that achieved the fastest inference time in previous benchmarking:

**mistral-7b-v0.3-bnb-4bit**

**Meta-Llama-3.1-8B-bnb-4bit**

**Llama-3.2-3B-bnb-4bit**

In [1]:
import os
import sys
import json
import time
import pandas as pd
from datasets import Dataset
sys.path.insert(1, '../')
from trl import SFTTrainer, SFTConfig
# from transformers import TrainingArguments
from unsloth import is_bfloat16_supported
from common import get_test_dataset, get_prompt_template, is_command_classification_correct, to_output_version_1
from unsloth import FastLanguageModel
from unsloth import apply_chat_template
from unsloth import standardize_sharegpt
# import torch
import itertools, json, shutil, os
import wandb
max_seq_length = 2048
dtype = None
load_in_4bit = True # 4bit quantization to reduce memory usage

os.environ['UNSLOTH_RETURN_LOGITS'] = '1'

/home/danielhenel/jarvis/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-05-05 01:29:32.771072: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-05-05 01:29:32.777519: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1746401372.786718 1554803 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1746401372.789489 1554803 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1746401372.797929 1554803 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746401372.797937 1554803 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746401372.797938 1554803 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1746401372.797939 1554803 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-05-05 01:29:32.800586: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/tmp/ipykernel_1554803/2707900335.py:10: UserWarning: WARNING: Unsloth should be imported before trl, transformers, peft to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from unsloth import is_bfloat16_supported

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

### Prepare train and test subsets

Dataset: Basic commands v2.0

Commands: START, STOP, START_ENGINE, STOP_ENGINE, CRANK_REQUEST

Train 80 - Test 20 split

In [2]:
def get_train_data(tokenizer):
    with open("../data/basic_commands_train_v2.0.json", 'r') as file:
        raw_train_dataset = json.load(file)

    chat_template = """{SYSTEM}
    USER: {INPUT}
    ASSISTANT: {OUTPUT}"""

    system_prompt = get_prompt_template(command_list=["STOP", "START", "ENGINE_STOP", "ENGINE_START", "CRANK_REQUEST"], prompt_version=2)
    system_prompt = system_prompt.replace("'null'", "null")

    train_data = []
    for command_class in raw_train_dataset:
        for input, output in raw_train_dataset[command_class].items():
            if input and output:
                output= output.replace("None", "null")
                output = json.loads(output)
                output = json.dumps(output)
                train_data.append({
                    "conversations": [
                        {"from": "user", "content": str(input)},
                        {"from": "assistant", "content": str(output)}
                    ]
                })

    train_data = Dataset.from_list(train_data)

    train_data = standardize_sharegpt(train_data)

    train_data = apply_chat_template(
        train_data,
        tokenizer = tokenizer,
        chat_template = chat_template,
        default_system_message = system_prompt
    )

    return train_data


def get_test_data():
    with open("../data/basic_commands_test_v2.0.json", 'r') as file:
        raw_test_dataset = json.load(file)
    test_data = []
    for command_class in raw_test_dataset:
        for input, output in raw_test_dataset[command_class].items():
            if input and output:
                output= output.replace("None", "null")
                output = json.loads(output)
                output = json.dumps(output)
                test_data.append({"input": str(input), "command_class": command_class})
    return test_data

### Model, tokenizer and trainer configuration

##### We test various configurations of the following params:
rank(r)

learning rate (lr)

gradient_accumulation_steps (grad_steps) 

number of epochs (epoch)

lora_alpha (alpha)

##### Then we evaluate the accuracy of each model agains our test dataset
##### Finally, we select the model of best accuracy

In [3]:
def get_model_and_tokenizer(model_name: str, r: int, alpha: int) -> tuple:
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name =  model_name,
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r = r,
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj",],
        lora_alpha = alpha,
        lora_dropout = 0,
        bias = "none",
        use_gradient_checkpointing = "unsloth",
        random_state = 3407,
        use_rslora = False,
        loftq_config = None,
    )
    return (model, tokenizer)

def get_training_args(lr: float, epoch: int, grad_steps: int, output_dir: str, run_name: str) -> SFTConfig:
    args = SFTConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = grad_steps,
        num_train_epochs = epoch,
        learning_rate = lr,
        output_dir=output_dir,
        logging_steps = 5,
        save_strategy="epoch",
        save_total_limit=1,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        report_to = "wandb",
        dataset_text_field = "text",
        dataset_num_proc = 2,
        packing = False,
        max_seq_length=2048,
        run_name=run_name,
        warmup_steps = 5,
        seed = 3407,
    )
    return args

### Training and evaluation

In [4]:
results = {}

def prompt_model(model, tokenizer, messages):
    FastLanguageModel.for_inference(model)

    input_ids = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt = True,
        return_tensors = "pt",
    ).to("cuda")

    output_ids = model.generate(
    input_ids,
    max_new_tokens=128,
    pad_token_id=tokenizer.eos_token_id
    )
    generated_ids = output_ids[0][input_ids.shape[-1]:]
    output_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    generated_text = tokenizer.decode(generated_ids, skip_special_tokens=True)
    return generated_text

def benchmark_model(model, tokenizer):
    test_dataset = get_test_data()
    predictions = {
        'Classification Result': [],
        'Prompt processing time': []
    }

    probability_threshold = 0.80

    
    for i in range(len(test_dataset)):

        messages=[
            {"role": "system",  "content": get_prompt_template(command_list=["STOP", "START", "ENGINE_STOP", "ENGINE_START", "CRANK_REQUEST"], prompt_version=2)},
            {"role": "user",  "content": test_dataset[i]['input']},]
        
        start_time = time.time() 
        response = prompt_model(model, tokenizer, messages)
        end_time = time.time()
        prompt_processing_time = end_time - start_time 
        answer = to_output_version_1(response)
        classification_result = is_command_classification_correct(answer, [test_dataset[i]["command_class"], None], probability_threshold)
        predictions['Classification Result'].append(classification_result[0])
        predictions['Prompt processing time'].append(prompt_processing_time)

    predictions = pd.DataFrame(predictions)
    accuracy = predictions[predictions['Classification Result'] == "CLASSIFICATION_CORRECT"].shape[0] / predictions.shape[0] 
    accuracy *= 100 # as percentage
    avg_processing_time = predictions['Prompt processing time'].mean()

    return (accuracy, avg_processing_time)

In [5]:
unsloth_4bit_models = [
    "./models/Llama-3.2-3B-bnb-4bit",
    "./models/mistral-7b-v0.3-bnb-4bit",
    "./models/Meta-Llama-3.1-8B-bnb-4bit"
]
learning_rates = [1e-5, 5e-5]
epochs = [2, 3]
grad_acc_steps = [4, 8]
r_values = [16, 32]

param_grid = list(itertools.product(learning_rates, epochs, grad_acc_steps, r_values))

results = []
best_accuracy = -float("inf")
best_model_dir = None

for model_name in unsloth_4bit_models:
    for lr, epoch, grad_steps, r in param_grid:
        alpha = r
        run_name = f"{model_name}_lr{lr}_ep{epoch}_gs{grad_steps}_r{r}_alpha{alpha}"
        output_dir = f"outputs/{run_name}"
        print(f"\nRunning config for {model_name}: {run_name}")

        # Initialize WandB
        wandb.init(mode="offline", name=run_name, reinit=True)

        # Get model and tokenizer
        model, tokenizer = get_model_and_tokenizer(model_name, r, alpha)

        # Get train, test and validation data
        train_dataset = get_train_data(tokenizer) 

        # Train and evaluate
        trainer = SFTTrainer(
            model = model,
            tokenizer = tokenizer,
            train_dataset=train_dataset,
            args = get_training_args(lr, epoch, grad_steps, output_dir, run_name)
        )
        trainer.train()

        # Evaluate on the test dataset
        test_accuracy, avg_processing_time = benchmark_model(model, tokenizer)

        # Log metrics to WandB
        wandb.log({
            "eval_accuracy": test_accuracy,
            "learning_rate": lr,
            "epochs": epoch,
            "grad_acc_steps": grad_steps,
            "r": r,
            "lora_alpha": alpha,
            "avg_processing_time" : avg_processing_time
        })

        # Save to results
        results.append({
            "model_name": model_name,
            "lr": lr,
            "epochs": epoch,
            "grad_acc_steps": grad_steps,
            "r": r,
            "alpha": alpha,
            'eval_accuracy': test_accuracy,
            "output_dir": output_dir,
            "avg_processing_time" : avg_processing_time,
        })

        # Save best model checkpoint
        if test_accuracy > best_accuracy:
            print(f"New best model found at {output_dir} (eval_accuracy={test_accuracy:.4f})")
            best_model_dir = output_dir
            best_accuracy = test_accuracy
            if os.path.exists("best_model_checkpoint"):
                shutil.rmtree("best_model_checkpoint")
            shutil.copytree(output_dir, "best_model_checkpoint")

        wandb.finish()

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2025.4.4 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 3549.06 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 33007.34 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 5154.64 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1055.43 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 945.46 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3748.95 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16 (eval_accuracy=0.5814)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 3074.29 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 41197.02 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 4152.61 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1038.06 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 911.94 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3220.35 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32 (eval_accuracy=3.4884)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2959.44 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38509.38 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3781.87 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 957.59 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 838.95 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3036.49 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2926.40 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38334.43 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3777.47 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 963.31 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 837.43 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2958.34 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2856.13 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38067.12 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3580.59 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 927.37 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 818.23 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2759.73 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16 (eval_accuracy=16.2791)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2914.13 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39232.97 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3609.82 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 933.82 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 812.39 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2905.76 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2834.13 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39905.07 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3546.48 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 927.80 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 801.90 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2840.19 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2888.90 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40166.75 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3735.66 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 937.37 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 822.65 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2958.13 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2850.51 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39475.53 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3505.98 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 952.36 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 816.84 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2857.55 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16 (eval_accuracy=60.4651)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2847.22 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38235.54 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3517.61 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 944.21 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 816.84 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2935.33 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32 (eval_accuracy=67.4419)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2838.66 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39694.65 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3565.33 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 949.41 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 811.42 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2813.09 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2847.81 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37910.22 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3564.14 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 896.78 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 774.63 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2871.44 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2823.82 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37590.38 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3550.98 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 946.46 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 811.22 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2928.21 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16 (eval_accuracy=69.7674)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2834.93 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 36028.91 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3711.34 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 944.50 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 817.52 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2912.89 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32 (eval_accuracy=73.2558)

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2853.86 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37539.08 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3617.77 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 897.78 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 787.34 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2881.27 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 24,313,856/3,000,000,000 (0.81% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Llama-3.2-3B-bnb-4bit: ./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2864.20 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 36380.83 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3599.58 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 943.63 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 815.38 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2964.78 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 48,627,712/3,000,000,000 (1.62% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2025.4.4 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.
Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2760.11 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 34620.46 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3543.44 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2215.67 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1659.41 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2672.00 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2757.34 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39568.91 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3637.04 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2330.23 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1772.04 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2721.43 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2744.26 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39903.40 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3520.54 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2327.67 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1668.59 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2625.00 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2726.51 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40517.79 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3601.16 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2295.43 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1739.34 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2637.43 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2663.09 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38866.23 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3351.70 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2274.50 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1706.49 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2639.12 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2685.17 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40316.77 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3418.08 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2244.74 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1724.35 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2614.29 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2774.49 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39291.17 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3445.83 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2311.50 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1741.73 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2692.78 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2726.79 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39796.26 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3347.88 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2250.21 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1718.64 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2592.39 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2750.22 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37844.51 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3449.98 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2234.15 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1791.13 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2626.60 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

New best model found at outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16 (eval_accuracy=75.5814)

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2746.70 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40446.75 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3495.65 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2233.00 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1757.00 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2677.98 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

New best model found at outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32 (eval_accuracy=76.7442)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2729.37 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40468.49 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3456.11 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2370.80 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1703.05 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2642.95 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2765.36 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38573.25 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3371.56 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2299.94 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1749.06 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2620.53 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2741.57 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39707.32 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3534.19 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2308.58 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1725.93 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2707.53 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2747.54 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37931.33 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3409.16 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2320.06 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1709.75 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2588.03 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2677.00 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38182.97 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3461.74 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2324.77 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1737.86 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2623.48 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/7,000,000,000 (0.60% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/mistral-7b-v0.3-bnb-4bit: ./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Mistral patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2722.63 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40642.71 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3508.70 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2349.76 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 1728.54 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2657.81 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/7,000,000,000 (1.20% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2838.42 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 40950.50 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3542.54 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 958.73 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 834.12 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2900.63 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2845.37 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37081.65 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3489.55 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 940.19 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 815.27 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2881.23 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2736.15 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 38981.16 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3544.18 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 886.95 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 797.11 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2778.82 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2719.50 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39220.06 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3425.41 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 935.47 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 808.33 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2810.95 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2720.82 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39085.55 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3482.51 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 888.42 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 772.78 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2752.21 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2746.25 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39164.75 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3463.34 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 890.93 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 772.20 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2755.79 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2689.32 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37481.04 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3482.14 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 863.77 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 780.25 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2789.70 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2753.51 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 36554.24 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3466.16 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 897.91 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 789.18 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2814.02 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2747.00 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 36567.79 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3446.63 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 855.55 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 783.36 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2414.34 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2709.18 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 35650.38 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3392.31 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 892.86 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 773.42 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2781.48 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 170
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2653.08 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37415.83 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3420.45 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 861.54 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 752.53 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2766.15 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2685.62 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 39233.51 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3406.56 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 911.69 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 778.05 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2703.92 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 2 | Total steps = 84
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2698.12 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37238.05 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3332.16 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 882.68 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 749.16 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2755.09 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2712.71 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37428.56 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3364.71 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 894.77 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 774.89 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2718.98 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 255
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2695.34 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 37173.69 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3396.86 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 874.35 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 766.48 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2695.87 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 41,943,040/8,000,000,000 (0.52% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

Running config for ./models/Meta-Llama-3.1-8B-bnb-4bit: ./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32

==((====))==  Unsloth 2025.4.4: Fast Llama patching. Transformers: 4.51.0.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth: Standardizing formats (num_proc=32): 100%|██████████| 682/682 [00:00<00:00, 2704.41 examples/s]
Unsloth: We automatically added an EOS token to stop endless generations.
Map: 100%|██████████| 682/682 [00:00<00:00, 36712.81 examples/s]
/tmp/ipykernel_1554803/1184755956.py:34: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  trainer = SFTTrainer(
Converting train dataset to ChatML (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 3374.94 examples/s]
Applying chat template to train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 879.72 examples/s]
Tokenizing train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 792.54 examples/s]
Truncating train dataset (num_proc=2): 100%|██████████| 682/682 [00:00<00:00, 2699.25 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 682 | Num Epochs = 3 | Total steps = 126
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 8 x 1) = 16
 "-____-"     Trainable parameters = 83,886,080/8,000,000,000 (1.05% trained)

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

### Results

In [6]:
results.sort(key=lambda x: x['eval_accuracy'], reverse=True)

for result in results:
    print("Result:")
    for key, value in result.items():
        print(f"  {key}: {value}")
    print("-" * 40)

Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 76.74418604651163
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.9205843002297157
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 76.16279069767442
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.9171388648277106
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 75.5813953488372
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.8819990740265957
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 75.5813953488372
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.8818630146425824
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 75.0
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.893469860387403
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 75.0
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.8699219504068064
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 73.25581395348837
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.6698440257893052
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 72.67441860465115
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 0.9146915355394053
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 72.67441860465115
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.8613221603770589
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 71.51162790697676
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.8466486431831537
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 70.34883720930233
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 0.8610484530759412
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 69.76744186046511
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.6925813001255656
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 68.6046511627907
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.8730736776839855
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 67.44186046511628
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.6873282069383666
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 65.69767441860465
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 0.8013046009596004
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 65.11627906976744
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.9266771882079369
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 65.11627906976744
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.9066914430884427
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 62.7906976744186
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.6650880589041599
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 60.46511627906976
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.6737832607224931
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 59.883720930232556
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 0.871684264305026
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 56.97674418604651
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 0.7892603569252546
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 56.395348837209305
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 0.6577288439107496
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 55.23255813953488
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.9148572087287903
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 52.32558139534884
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.8757081322891768
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 51.162790697674424
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 0.6736371960750845
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 47.674418604651166
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.8896363876586737
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 42.44186046511628
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.9187790806903395
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 37.2093023255814
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 0.6337143501570058
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 36.04651162790697
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 0.8993269288262655
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 28.488372093023255
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 0.8703303101450898
----------------------------------------
Result:
  model_name: ./models/mistral-7b-v0.3-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 21.511627906976745
  output_dir: outputs/./models/mistral-7b-v0.3-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 0.8686480037001676
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 20.348837209302324
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.49295420286267305
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 16.27906976744186
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.807687099589858
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 16.27906976744186
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.7719913263653599
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 5e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 15.69767441860465
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr5e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 0.300987089789191
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 14.534883720930234
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.45744306264921675
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 11.627906976744185
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 0.6312964322955109
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 9.30232558139535
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.3362606999485992
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 5.232558139534884
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs4_r16_alpha16
  avg_processing_time: 0.27969336786935495
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 4.651162790697675
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep3_gs4_r32_alpha32
  avg_processing_time: 0.2382411333017571
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 32
  alpha: 32
  eval_accuracy: 3.488372093023256
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r32_alpha32
  avg_processing_time: 0.8213131275287894
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 2.3255813953488373
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 0.7914110574611398
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 4
  r: 16
  alpha: 16
  eval_accuracy: 0.5813953488372093
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs4_r16_alpha16
  avg_processing_time: 0.9790162513422411
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 0.5813953488372093
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs8_r32_alpha32
  avg_processing_time: 0.8935119925543319
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 0.0
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 1.9918705197267754
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 32
  alpha: 32
  eval_accuracy: 0.0
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep2_gs8_r32_alpha32
  avg_processing_time: 1.9862451608790908
----------------------------------------
Result:
  model_name: ./models/Llama-3.2-3B-bnb-4bit
  lr: 1e-05
  epochs: 3
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 0.0
  output_dir: outputs/./models/Llama-3.2-3B-bnb-4bit_lr1e-05_ep3_gs8_r16_alpha16
  avg_processing_time: 1.8926950429761134
----------------------------------------
Result:
  model_name: ./models/Meta-Llama-3.1-8B-bnb-4bit
  lr: 1e-05
  epochs: 2
  grad_acc_steps: 8
  r: 16
  alpha: 16
  eval_accuracy: 0.0
  output_dir: outputs/./models/Meta-Llama-3.1-8B-bnb-4bit_lr1e-05_ep2_gs8_r16_alpha16
  avg_processing_time: 1.9471905744353006
----------------------------------------